name: vid2frame
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - freetype=2.10.4
  - h5py=2.10.0
  - hdf5=1.10.6
  - intel-openmp=2020.2
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=8.1.2
  - pip=21.0.1
  - python=3.7.10
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.3
  - tk=8.6.10
  - tqdm=4.59.0
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - imagehash==4.2.0
    - lmdb==1.1.1
    - pillow-simd==7.0.0.post3
    - pywavelets==1.1.1
    - scipy==1.6.2
